### ISSUE TITLE
Renaming output/stream

### ISSUE THREAD

**Issue by srpwnd** [Matatika/tap-google-sheets#11]
I wanted to rename my output stream (using env var). In [docs on Meltano Hub](https://hub.meltano.com/extractors/tap-google-sheets#output_name-setting) it says to use `TAP_GOOGLE_SHEETS_OUTPUT_NAME`. In your [README here](https://github.com/Matatika/tap-google-sheets#environment-variable) it says to use `TAP_GOOGLE_SHEETS_STREAM_NAME`.

I went to check the code and saw that the [code expects config to have property](https://github.com/Matatika/tap-google-sheets/blob/master/tap_google_sheets/tap.py#L36) `output_name` but then [tries to read config for key](https://github.com/Matatika/tap-google-sheets/blob/master/tap_google_sheets/tap.py#L60) `stream_name` which does not exist. Am I missing something?

I can make a PR to adjust this if it is welcome.

**Comment by ReubenFrankel** [comment]
Hi @srpwnd, thanks for opening this issue. Looks like a bug to me - happy to accept a PR!

In the meantime, since this tap was built with the Meltano SDK you should be able to use `stream_maps` to [alias a stream](https://sdk.meltano.com/en/v0.26.0/stream_maps.html#aliasing-a-stream-using-alias):

```yml
plugins:
  extractors:
  - name: tap-google-sheets
    variant: matatika
    pip_url: git+https://github.com/Matatika/tap-google-sheets.git
    config:
      stream_maps:
        example_sheet:  # sheet name (spaces replaced with underscores)
          __alias__: example_stream  # stream name
```
